// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/suburb-intel/CleanPlatform.tsx": () => import("../components/mockups/suburb-intel/CleanPlatform.tsx"),
  "./components/mockups/suburb-intel/DarkTerminal.tsx": () => import("../components/mockups/suburb-intel/DarkTerminal.tsx"),
  "./components/mockups/suburb-intel/WarmIntelligence.tsx": () => import("../components/mockups/suburb-intel/WarmIntelligence.tsx")
};
